// toolchain/cli/templates/react-java/ui-src/src/App.tsx
import { useState } from 'react'
import {
  GoldButton,
  Page,
  PageHeader,
  PluginBar,
  PluginShell,
  StatusBar,
  useFengYuClient,
} from '@infinia/plugin-ui'

/**
 * {{pluginName}} — a FengYu plugin with a React UI backed by a Java JSON-RPC worker.
 *
 * The UI calls the worker's `hello` method through the host RPC bridge and
 * displays the returned greeting. This is the smallest end-to-end wiring of
 * UI → host → worker; real plugins add file pickers, task tables, etc.
 * Chrome: the focused-workbench shell (no sidebar) — views live in the top
 * focus bar when a plugin grows beyond one view.
 *
 * Plugin id: {{pluginId}}
 */
export default function App() {
  const client = useFengYuClient()
  const [view, setView] = useState('home')
  const [greeting, setGreeting] = useState('')
  const [busy, setBusy] = useState(false)

  async function sayHello(): Promise<void> {
    setBusy(true)
    try {
      const result = await client.invoke<{ message: string }>('hello', { name: 'FengYu' })
      setGreeting(result.message)
    } catch (error) {
      setGreeting(String(error))
    } finally {
      setBusy(false)
    }
  }

  return (
    <PluginShell>
      <PluginBar
        active={view}
        onNavigate={setView}
        tabs={[{ value: 'home', title: '主页' }]}
      />
      <Page>
        <PageHeader
          title="Hello, worker"
          description="最小端到端链路：UI → 宿主 RPC → Java worker。"
          right={
            <GoldButton disabled={busy} onClick={() => void sayHello()} data-action="hello">
              {busy ? '调用中…' : '调用 hello'}
            </GoldButton>
          }
        />
        {greeting ? (
          <p data-greeting="" className="rounded-xl border border-line bg-panel px-4 py-3 text-[14px]">
            {greeting}
          </p>
        ) : null}
      </Page>
      <StatusBar left={<span>worker 127.0.0.1:24057</span>} right={<span>{{pluginId}}</span>} />
    </PluginShell>
  )
}

// toolchain/cli/templates/vue-java/ui-src/src/App.vue
<script setup lang="ts">
/**
 * {{pluginName}} — a FengYu plugin with a Vue UI backed by a Java JSON-RPC worker.
 *
 * The UI calls the worker's `hello` method through the host RPC bridge and
 * displays the returned greeting. This is the smallest end-to-end wiring of
 * UI → host → worker; real plugins add file pickers, task tables, etc.
 *
 * Plugin id: {{pluginId}}
 */
import { ref } from 'vue'
import { FyPluginPage, FyPluginShell, FyPageHeader, FyProgress, useFengYuClient } from '@infinia/plugin-ui'

const client = useFengYuClient()
const greeting = ref('')
const busy = ref(false)

async function sayHello(): Promise<void> {
  busy.value = true
  try {
    const result = await client.invoke<{ message: string }>('hello', { name: 'FengYu' })
    greeting.value = result.message
  } catch (error) {
    greeting.value = String(error)
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <FyPluginShell title="{{pluginName}}" :items="[{ value: 'home', title: 'Home', icon: 'mdi-home-outline' }]">
    <FyPluginPage>
      <FyPageHeader title="{{pluginName}}" description="A FengYu plugin with a Vue UI and a Java worker." />
      <v-btn color="primary" variant="flat" prepend-icon="mdi-hand-wave" :loading="busy" @click="sayHello">
        Say hello
      </v-btn>
      <FyProgress v-if="busy" label="Contacting worker…" class="mt-4" />
      <p v-if="greeting" class="mt-4 text-h6">{{ greeting }}</p>
    </FyPluginPage>
  </FyPluginShell>
</template>
