// frontend/src/components/chat/MentionPanel.tsx
import { useEffect, useRef } from 'react'
import { useTranslation } from 'react-i18next'
import { Code2, FileImage, FileText, Folder, Wand2, Workflow } from 'lucide-react'
import type { MentionOption, MentionSection } from '@/lib/mentionSearch'
import { cn } from '@/lib/utils'

/**
 * Completion panel (ZCode's MentionPanel structure): group headers when more than one group,
 * 34px option rows, hover independent of the keyboard-selected index. The parent owns
 * selection state; this panel renders and reports mouse interactions (mousedown prevents
 * editor focus loss).
 */
export function optionIcon(option: MentionOption) {
  if (option.category === 'skill') return <Wand2 size={15} />
  if (option.category === 'plugin') return <Code2 size={15} />
  if (option.category === 'flow') return <Workflow size={15} />
  if (option.isDirectory) return <Folder size={15} />
  const ext = option.label.split('.').pop()?.toLowerCase() ?? ''
  if (['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'ico', 'pdf'].includes(ext)) return <FileImage size={15} />
  return <FileText size={15} />
}

export default function MentionPanel({ sections, selectedIndex, loading, emptyLabel, onSelect, onHover }: {
  sections: MentionSection[]
  selectedIndex: number
  loading: boolean
  emptyLabel: string
  onSelect: (option: MentionOption) => void
  onHover: (index: number) => void
}) {
  const { t } = useTranslation()
  const listRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    listRef.current?.querySelector('[data-selected="true"]')?.scrollIntoView({ block: 'nearest' })
  }, [selectedIndex])

  const categoryLabels: Record<string, string> = {
    file: t('aichat.mentionFiles'),
    plugin: t('aichat.mentionPlugins'),
    skill: t('aichat.mentionSkills'),
    flow: t('aichat.mentionFlows'),
  }

  let flatIndex = -1
  return (
    <div className="cx-card mention-panel" role="listbox" aria-label={t('aichat.mentionPanel')}>
      <div className="mention-panel__list" ref={listRef}>
        {sections.map(section => (
          <div key={section.category}>
            {sections.length > 1 && (
              <div className="mention-panel__header" aria-hidden="true">
                {categoryLabels[section.category] ?? section.category}
              </div>
            )}
            {section.options.map(option => {
              flatIndex += 1
              const index = flatIndex
              const selected = index === selectedIndex
              return (
                <button
                  key={option.id}
                  role="option"
                  aria-selected={selected}
                  data-selected={selected}
                  className={cn('mention-panel__option', { 'mention-panel__option--selected': selected })}
                  onMouseDown={event => event.preventDefault()}
                  onMouseEnter={() => onHover(index)}
                  onClick={() => onSelect(option)}
                >
                  <span className="mention-panel__icon">{optionIcon(option)}</span>
                  <span className="mention-panel__label">{option.label}</span>
                  <span className="cx-muted mention-panel__description" title={option.description}>{option.description}</span>
                </button>
              )
            })}
          </div>
        ))}
        {loading && <div className="cx-muted mention-panel__status"><span className="cx-spin" /> {t('common.loading')}</div>}
        {!loading && sections.length === 0 && <div className="cx-muted mention-panel__status">{emptyLabel}</div>}
      </div>
    </div>
  )
}

// archive/frontend-vue/src/components/chat/MentionPanel.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { watch, ref } from 'vue'
import type { MentionOption, MentionSection } from './mentionSearch'

/**
 * Mention completion panel, ported from ZCode's MentionPanel structure: grouped rows (group
 * headers only when more than one group), 34px option rows with label + weak description,
 * hover state independent of the keyboard-selected state. The parent owns selection state —
 * keyboard navigation happens on the textarea's keydown, this panel only renders and reports
 * mouse interactions (mousedown prevents focus loss from the textarea, per ZCode).
 */
const props = defineProps<{
  sections: MentionSection[]
  /** Index into the flattened option list across all sections. */
  selectedIndex: number
  loading: boolean
  /** Shown when no option matches (query) or before typing (hint). */
  emptyLabel: string
}>()
const emit = defineEmits<{
  select: [option: MentionOption]
  hover: [index: number]
}>()
const { t } = useI18n()

const CATEGORY_LABEL_KEYS: Record<string, string> = {
  file: 'aichat.mentionFiles',
  plugin: 'aichat.mentionPlugins',
  skill: 'aichat.mentionSkills',
  flow: 'aichat.mentionFlows',
}

/** [globalIndex, option] pairs so each row knows its position in the flattened order. */
function rows(section: MentionSection, sectionStart: number): { index: number; option: MentionOption }[] {
  return section.options.map((option, i) => ({ index: sectionStart + i, option }))
}

/** Offset of a section's first option in the flattened (keyboard-navigable) order. */
function sectionOffset(sectionIndex: number): number {
  let count = 0
  for (let i = 0; i < sectionIndex; i++) count += props.sections[i].options.length
  return count
}

const listRef = ref<HTMLElement | null>(null)
watch(() => props.selectedIndex, () => {
  listRef.value?.querySelector('[data-selected="true"]')?.scrollIntoView({ block: 'nearest' })
})
</script>

<template>
  <div class="cx-card mention-panel" role="listbox" :aria-label="t('aichat.mentionPanel')">
    <div ref="listRef" class="mention-panel__list">
      <template v-for="(section, sectionIndex) in sections" :key="section.category">
        <div v-if="sections.length > 1" class="mention-panel__header" aria-hidden="true">
          {{ t(CATEGORY_LABEL_KEYS[section.category] ?? 'aichat.mentionFiles') }}
        </div>
        <button
          v-for="{ index, option } in rows(section, sectionOffset(sectionIndex))"
          :key="option.id"
          class="mention-panel__option"
          :class="{ 'mention-panel__option--selected': index === selectedIndex }"
          role="option"
          :aria-selected="index === selectedIndex"
          :data-selected="index === selectedIndex"
          @mousedown.prevent
          @mouseenter="emit('hover', index)"
          @click="emit('select', option)"
        >
          <i class="mdi mention-panel__icon" :class="option.icon" aria-hidden="true" />
          <span class="mention-panel__label">{{ option.label }}</span>
          <span class="cx-muted mention-panel__description" :title="option.description">{{ option.description }}</span>
        </button>
      </template>
      <div v-if="loading" class="cx-muted mention-panel__status"><span class="cx-spin" /> {{ $t('common.loading') }}</div>
      <div v-else-if="sections.length === 0" class="cx-muted mention-panel__status">{{ emptyLabel }}</div>
    </div>
  </div>
</template>

<style scoped>
.mention-panel {
  overflow: hidden;
  padding: 5px;
}
.mention-panel__list {
  max-height: 224px;
  overflow-y: auto;
}
.mention-panel__header {
  height: 32px;
  display: flex;
  align-items: center;
  padding: 0 9px;
  font-size: 11px;
  font-weight: 650;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: rgb(var(--v-theme-secondary));
  opacity: 0.75;
}
.mention-panel__option {
  width: 100%;
  height: 34px;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 0 9px;
  border: 0;
  border-radius: var(--cx-radius-sm);
  background: transparent;
  color: rgb(var(--v-theme-on-surface));
  font: inherit;
  font-size: 12.5px;
  text-align: left;
  cursor: pointer;
}
.mention-panel__option:hover { background: var(--cx-hover); }
.mention-panel__option--selected { background: var(--cx-hover-strong); }
.mention-panel__option:focus-visible {
  outline: 2px solid rgba(var(--v-theme-on-surface), 0.72);
  outline-offset: -2px;
}
.mention-panel__icon { font-size: 17px; flex: 0 0 auto; opacity: 0.8; }
.mention-panel__label {
  flex: 0 1 auto;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.mention-panel__description {
  flex: 1 1 auto;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 11.5px;
  text-align: right;
}
.mention-panel__status {
  height: 36px;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 0 9px;
  font-size: 12px;
}
</style>
