// frontend/src/components/agent/FlowVariableTree.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import {
  flowTypeColor,
  flowTypeCompatible,
  normalizeFlowType,
  workflowNodeTitle,
  workflowOutputTree,
  type FlowOutputField,
  type FlowValueType,
  type WorkflowFlowNode,
  type WorkflowSchemaProperty,
} from './workflow'

/**
 * The reference picker (Dify's getNodeAvailableVars + n8n's schema view): upstream
 * outputs as a recursive tree, grouped by source node, filtered by the target
 * input's expected type. Rows are clickable (bind), draggable (drag-to-map onto
 * an input), and carry a copy-path affordance for the expression editor.
 */
const props = defineProps<{
  nodes: WorkflowFlowNode[]
  workflowSchemaFields: Array<[string, WorkflowSchemaProperty]>
  /** Type the target input expects; mismatched rows gray out with a reason. */
  expectedType?: string | null
  disabled?: boolean
}>()
const emit = defineEmits<{
  select: [selection: { kind: 'input' | 'node'; nodeId?: string; path?: string; type: FlowValueType }]
}>()

const { t } = useI18n()
const search = ref('')
const expanded = ref(new Set<string>())

interface TreeRow {
  key: string
  depth: number
  title: string
  path: string
  type: FlowValueType
  examples: unknown[]
  expandable: boolean
  nodeId?: string
  inputName?: string
}

function flattenFields(nodeId: string, fields: FlowOutputField[], depth: number, out: TreeRow[]): void {
  for (const field of fields) {
    const key = `${nodeId}${field.path}`
    out.push({
      key,
      depth,
      title: field.title,
      path: field.path,
      type: field.type,
      examples: field.examples,
      expandable: !!field.children?.length,
      nodeId,
    })
    if (field.children?.length && expanded.value.has(key)) {
      flattenFields(nodeId, field.children, depth + 1, out)
    }
  }
}

const searchNeedle = computed(() => search.value.trim().toLocaleLowerCase())
function matchesSearch(row: TreeRow): boolean {
  if (!searchNeedle.value) return true
  return `${row.title} ${row.path}`.toLocaleLowerCase().includes(searchNeedle.value)
}

const inputRows = computed<TreeRow[]>(() => props.workflowSchemaFields
  .filter(([name, schema]) => !searchNeedle.value
    || `${schema.title ?? ''} ${name}`.toLocaleLowerCase().includes(searchNeedle.value))
  .map(([name, schema]) => ({
    key: `input::${name}`,
    depth: 0,
    title: schema.title || name,
    path: name,
    type: (schema.format === 'fengyu-file' ? 'file' : schema.type) as FlowValueType,
    examples: [],
    expandable: false,
    inputName: name,
  })))

const nodeGroups = computed(() => {
  const groups: Array<{ node: WorkflowFlowNode; rows: TreeRow[] }> = []
  for (const node of props.nodes) {
    const rows: TreeRow[] = []
    // Whole-result row: binding the complete output object.
    rows.push({
      key: `${node.id}::complete`,
      depth: 0,
      title: t('agent.completeResult'),
      path: '',
      type: 'object',
      examples: [],
      expandable: false,
      nodeId: node.id,
    })
    flattenFields(node.id, workflowOutputTree(node), 0, rows)
    groups.push({ node, rows })
  }
  return groups
})

/** Every field fully expanded — used while searching so matches are never hidden. */
function allRowsFlat(node: WorkflowFlowNode): TreeRow[] {
  const saved = expanded.value
  expanded.value = new Set()
  const rows: TreeRow[] = [{
    key: `${node.id}::complete`,
    depth: 0,
    title: t('agent.completeResult'),
    path: '',
    type: 'object',
    examples: [],
    expandable: false,
    nodeId: node.id,
  }]
  flattenFields(node.id, workflowOutputTree(node), 0, rows)
  expanded.value = saved
  return rows
}

const visibleGroups = computed(() => nodeGroups.value
  .map((group) => ({
    node: group.node,
    rows: searchNeedle.value
      ? allRowsFlat(group.node).filter((row) => matchesSearch(row))
      : group.rows,
  }))
  .filter((group) => group.rows.length))

function compatible(row: TreeRow): boolean {
  if (row.inputName) {
    return !props.expectedType || flowTypeCompatible(props.expectedType, row.type)
  }
  return !props.expectedType || flowTypeCompatible(props.expectedType, row.type)
}

function typeLabel(row: TreeRow): string {
  return t(`agent.flowType.${normalizeFlowType(row.type)}`)
}

function exampleText(row: TreeRow): string {
  const example = row.examples[0]
  if (example === undefined || example === null) return ''
  const text = typeof example === 'string' ? example : JSON.stringify(example)
  return text.length > 40 ? `${text.slice(0, 37)}…` : text
}

function toggleExpand(row: TreeRow) {
  const next = new Set(expanded.value)
  if (next.has(row.key)) next.delete(row.key)
  else next.add(row.key)
  expanded.value = next
}

function selectRow(row: TreeRow) {
  if (props.disabled || !compatible(row)) return
  if (row.inputName) {
    emit('select', { kind: 'input', path: row.inputName, type: row.type })
    return
  }
  emit('select', { kind: 'node', nodeId: row.nodeId, path: row.path, type: row.type })
}

function copyRow(row: TreeRow) {
  const reference = row.inputName
    ? `{{inputs.${row.inputName}}}`
    : `{{node.${row.nodeId}.result${row.path}}}`
  void navigator.clipboard?.writeText(reference)
}

function onRowDragStart(event: DragEvent, row: TreeRow) {
  if (!event.dataTransfer || props.disabled || !compatible(row)) return
  const payload = row.inputName
    ? { kind: 'input', path: row.inputName, type: row.type }
    : { kind: 'node', nodeId: row.nodeId, path: row.path, type: row.type }
  event.dataTransfer.setData('application/x-fengyu-ref', JSON.stringify(payload))
  event.dataTransfer.effectAllowed = 'copy'
}
</script>

<template>
  <div class="fvt">
    <div class="fvt__search">
      <i class="mdi mdi-magnify" />
      <input v-model="search" :placeholder="t('agent.searchVariables')" :aria-label="t('agent.searchVariables')">
    </div>
    <div class="fvt__body">
      <div v-if="inputRows.length" class="fvt__group">
        <div class="fvt__group-head">
          <i class="mdi mdi-form-textbox" />
          <span>{{ t('agent.workflowInputSource') }}</span>
        </div>
        <div
          v-for="row in inputRows"
          :key="row.key"
          class="fvt__row"
          :class="{ 'fvt__row--muted': !compatible(row) }"
          :style="{ paddingInlineStart: `${8 + row.depth * 14}px` }"
          :title="compatible(row) ? t('agent.bindThisValue') : t('agent.typeMismatchHint', { type: typeLabel(row) })"
          draggable="true"
          @dragstart="onRowDragStart($event, row)"
          @click="selectRow(row)"
        >
          <span class="fvt__dot" :style="{ background: flowTypeColor(row.type) }" />
          <span class="fvt__name">{{ row.title }}</span>
          <span class="fvt__type">{{ typeLabel(row) }}</span>
          <button class="fvt__copy" :title="t('agent.copyReferencePath')" @click.stop="copyRow(row)"><i class="mdi mdi-content-copy" /></button>
        </div>
      </div>
      <div v-for="group in visibleGroups" :key="group.node.id" class="fvt__group">
        <div class="fvt__group-head">
          <i class="mdi mdi-hammer-wrench" />
          <span>{{ workflowNodeTitle(group.node) }}</span>
        </div>
        <div
          v-for="row in group.rows"
          :key="row.key"
          class="fvt__row"
          :class="{ 'fvt__row--muted': !compatible(row), 'fvt__row--branch': row.expandable }"
          :style="{ paddingInlineStart: `${8 + row.depth * 14}px` }"
          :title="compatible(row)
            ? exampleText(row) ? `${t('agent.exampleLabel')}: ${exampleText(row)}` : t('agent.bindThisValue')
            : t('agent.typeMismatchHint', { type: typeLabel(row) })"
          draggable="true"
          @dragstart="onRowDragStart($event, row)"
          @click="row.expandable ? toggleExpand(row) : selectRow(row)"
        >
          <button v-if="row.expandable" class="fvt__expand" :title="t('agent.toggleFields')" @click.stop="toggleExpand(row)">
            <i class="mdi" :class="expanded.has(row.key) ? 'mdi-menu-down' : 'mdi-menu-right'" />
          </button>
          <span v-else class="fvt__dot" :style="{ background: flowTypeColor(row.type) }" />
          <span class="fvt__name">{{ row.title }}</span>
          <span class="fvt__type">{{ typeLabel(row) }}</span>
          <button class="fvt__copy" :title="t('agent.copyReferencePath')" @click.stop="copyRow(row)"><i class="mdi mdi-content-copy" /></button>
        </div>
      </div>
      <div v-if="!visibleGroups.length && !inputRows.length" class="fvt__empty">
        {{ t('agent.variableTreeEmpty') }}
      </div>
    </div>
    <p class="fvt__hint">{{ t('agent.variableTreeHint') }}</p>
  </div>
</template>

<style scoped>
.fvt {
  display: flex;
  flex-direction: column;
  min-height: 0;
  border: 1px solid rgb(var(--v-theme-outline-variant));
  border-radius: 8px;
  background: rgb(var(--v-theme-surface));
}

.fvt__search {
  display: flex;
  gap: 7px;
  align-items: center;
  padding: 0 8px;
  border-bottom: 1px solid rgb(var(--v-theme-outline-variant));
  border-radius: 8px 8px 0 0;
  background: rgb(var(--v-theme-surface-container));
}

.fvt__search input {
  width: 100%;
  min-height: 32px;
  color: inherit;
  border: 0;
  outline: 0;
  background: transparent;
}

.fvt__body {
  max-height: 280px;
  overflow-y: auto;
  padding: 4px 0;
}

.fvt__group { margin-bottom: 4px; }

.fvt__group-head {
  display: flex;
  gap: 6px;
  align-items: center;
  padding: 6px 8px 3px;
  color: rgba(var(--v-theme-on-surface), .62);
  font-size: 10px;
  font-weight: 700;
}

.fvt__group-head i { font-size: 13px; color: rgb(var(--v-theme-primary)); }

.fvt__row {
  display: flex;
  gap: 6px;
  align-items: center;
  min-height: 28px;
  padding-block: 2px;
  padding-inline-end: 6px;
  font-size: 11px;
  cursor: pointer;
}

.fvt__row:hover { background: rgba(var(--v-theme-primary), .08); }

.fvt__row--muted {
  opacity: .45;
  cursor: not-allowed;
}

.fvt__row--branch .fvt__name { font-weight: 650; }

.fvt__dot {
  flex: 0 0 auto;
  width: 8px;
  height: 8px;
  border-radius: 50%;
}

.fvt__expand {
  display: grid;
  place-items: center;
  width: 16px;
  height: 20px;
  padding: 0;
  border: 0;
  background: transparent;
  color: rgba(var(--v-theme-on-surface), .6);
  cursor: pointer;
}

.fvt__name {
  min-width: 0;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.fvt__type {
  flex: 0 0 auto;
  color: rgba(var(--v-theme-on-surface), .5);
  font-size: 9px;
}

.fvt__copy {
  display: grid;
  place-items: center;
  width: 20px;
  height: 20px;
  padding: 0;
  border: 0;
  border-radius: 4px;
  background: transparent;
  color: rgba(var(--v-theme-on-surface), .45);
  cursor: pointer;
}

.fvt__copy:hover { color: rgb(var(--v-theme-primary)); background: rgba(var(--v-theme-primary), .1); }

.fvt__empty {
  padding: 16px 10px;
  color: rgba(var(--v-theme-on-surface), .55);
  font-size: 11px;
  text-align: center;
}

.fvt__hint {
  margin: 0;
  padding: 6px 8px;
  color: rgba(var(--v-theme-on-surface), .5);
  font-size: 9px;
  line-height: 1.4;
  border-top: 1px solid rgb(var(--v-theme-outline-variant));
}
</style>

// frontend/src/components/flow/FlowVariableTree.tsx
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { ChevronDown, ChevronRight, Copy } from 'lucide-react'
import {
  flowTypeColor,
  flowTypeCompatible,
  type FlowOutputField,
  type FlowValueType,
} from '@/lib/flowInspectorModel'

/**
 * The reference picker behind the inspector's Reference source mode (port of the
 * Vue FlowVariableTree): workflow inputs first, then per upstream node its input
 * tree, complete-result row, and output tree. Rows recurse through declared
 * children; type-compatible rows are bindable, mismatched ones grayed with a
 * tooltip; click binds, drag carries the `application/x-fengyu-ref` payload.
 */

export interface VariableTreeSelection {
  kind: 'input' | 'node'
  nodeId?: string
  source?: 'input' | 'result'
  path?: string
  /** Declared type at the selected path (type-compat display). */
  type?: FlowValueType
}

interface UpstreamGroup {
  nodeId: string
  title: string
  inputs: FlowOutputField[]
  outputs: FlowOutputField[]
}

export function FlowVariableTree(props: {
  /** The receiving node's expected input type (compatibility highlighting). */
  targetType?: FlowValueType | null
  workflowInputs: FlowOutputField[]
  upstreamNodes: Array<{ id: string; title: string; inputs: FlowOutputField[]; outputs: FlowOutputField[] }>
  onPick: (selection: VariableTreeSelection) => void
}) {
  const { t } = useTranslation()
  const [search, setSearch] = useState('')
  const query = search.trim().toLowerCase()

  const groups = useMemo<UpstreamGroup[]>(() => props.upstreamNodes.map((node) => ({
    nodeId: node.id,
    title: node.title,
    inputs: node.inputs,
    outputs: node.outputs,
  })), [props.upstreamNodes])

  const filterFields = (fields: FlowOutputField[]): FlowOutputField[] => {
    if (!query) return fields
    return fields.flatMap((field) => {
      const children = field.children ? filterFields(field.children) : []
      const selfHit = field.name.toLowerCase().includes(query)
        || field.title.toLowerCase().includes(query)
      return selfHit || children.length ? [{ ...field, children: children.length ? children : field.children }] : []
    })
  }

  const renderRow = (field: FlowOutputField, selection: VariableTreeSelection) => {
    const compatible = props.targetType == null
      || flowTypeCompatible(props.targetType, selection.type ?? field.type)
    const label = `${selection.kind === 'input' ? t('agent.workflowInputSource') : t('agent.nodeOutputSource')} · ${field.title}`
    return (
      <div key={`${selection.nodeId ?? 'wf'}:${selection.source}:${field.path}`} className="flow-vtree__row-wrap">
        <div
          className={`flow-vtree__row${compatible ? '' : ' flow-vtree__row--mismatch'}`}
          title={compatible ? undefined : t('agent.typeMismatchHint', {
            expected: props.targetType ?? 'any',
            actual: selection.type ?? field.type,
          })}
          draggable={compatible}
          onDragStart={(event) => {
            event.dataTransfer.setData('application/x-fengyu-ref', JSON.stringify(selection))
            event.dataTransfer.effectAllowed = 'copy'
          }}
          onClick={() => compatible && props.onPick(selection)}
          role="treeitem"
          aria-label={label}
        >
          <span className="flow-vtree__dot" style={{ background: flowTypeColor(selection.type ?? field.type) }} />
          <span className="flow-vtree__name">{field.title}</span>
          <span className="flow-vtree__type">{t(`agent.flowType.${selection.type ?? field.type}`)}</span>
          <button
            className="cx-iconbtn cx-iconbtn--sm flow-vtree__copy"
            title={t('agent.copyReferencePath')}
            onClick={(event) => {
              event.stopPropagation()
              const path = field.path.startsWith('.') ? field.path.slice(1) : field.path
              void navigator.clipboard?.writeText(selection.kind === 'input'
                ? `{{inputs.${path}}}`
                : `{{node.${selection.nodeId}.${selection.source}${field.path}}}`)
            }}
          >
            <Copy size={12} />
          </button>
        </div>
        {field.children?.map((child) => {
          // Child paths concatenate verbatim: `.a` + `.b` → `.a.b`; `.a` + `[0]` → `.a[0]`.
          const childSelection: VariableTreeSelection = {
            ...selection,
            path: `${field.path}${child.path}`,
            type: child.type,
          }
          return renderRow(child, childSelection)
        })}
      </div>
    )
  }

  const inputGroups = filterFields(props.workflowInputs)
  const shownGroups = groups.map((group) => ({
    ...group,
    inputs: filterFields(group.inputs),
    outputs: filterFields(group.outputs),
  }))

  return (
    <div className="flow-vtree" role="tree" aria-label={t('agent.searchVariables')}>
      <input
        className="cx-input flow-vtree__search"
        placeholder={t('agent.searchVariables')}
        value={search}
        onChange={(event) => setSearch(event.target.value)}
      />
      {!inputGroups.length && !shownGroups.length && (
        <p className="cx-muted flow-vtree__empty">{t('agent.variableTreeEmpty')}</p>
      )}
      {inputGroups.length > 0 && (
        <TreeGroup label={t('agent.workflowInputSource')} defaultOpen>
          {inputGroups.map((field) => renderRow(field, {
            kind: 'input', path: field.path.replace(/^\./, ''), type: field.type,
          }))}
        </TreeGroup>
      )}
      {shownGroups.map((group) => (
        <TreeGroup key={group.nodeId} label={group.title} defaultOpen={!query}>
          {group.inputs.map((field) => renderRow(field, {
            kind: 'node', nodeId: group.nodeId, source: 'input',
            path: field.path, type: field.type,
          }))}
          {group.outputs.length > 0 && (
            <div
              className="flow-vtree__row"
              onClick={() => props.onPick({ kind: 'node', nodeId: group.nodeId, source: 'result', path: '', type: 'object' })}
              role="treeitem"
            >
              <span className="flow-vtree__dot" style={{ background: flowTypeColor('object') }} />
              <span className="flow-vtree__name">{t('agent.completeResult')}</span>
              <span className="flow-vtree__type">{t('agent.flowType.object')}</span>
            </div>
          )}
          {group.outputs.map((field) => renderRow(field, {
            kind: 'node', nodeId: group.nodeId, source: 'result',
            path: field.path, type: field.type,
          }))}
        </TreeGroup>
      ))}
      <p className="cx-muted flow-vtree__hint">{t('agent.variableTreeHint')}</p>
    </div>
  )
}

function TreeGroup(props: { label: string; defaultOpen?: boolean; children: React.ReactNode }) {
  const [open, setOpen] = useState(!!props.defaultOpen)
  return (
    <div className="flow-vtree__group">
      <button className="flow-vtree__group-head" onClick={() => setOpen(!open)}>
        {open ? <ChevronDown size={13} /> : <ChevronRight size={13} />}
        <span>{props.label}</span>
      </button>
      {open && <div className="flow-vtree__group-body">{props.children}</div>}
    </div>
  )
}
