// frontend/src/components/agent/FlowRunDialog.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { api } from '@/api/client'
import type {
  ActiveFileEntry,
  AgentRunFile,
  AiPermissionMode,
} from '@/api/types'
import {
  humanizeWorkflowField,
  isWorkflowValueConfigured,
  parseWorkflowArguments,
  parseWorkflowSchema,
  type WorkflowEnumSource,
  type WorkflowSchemaProperty,
} from '@/components/agent/workflow'

/**
 * Flowise-style run dialog: renders the workflow's input schema as a friendly
 * form (file pickers, plugin-sourced dropdowns, Excel-analyzed candidates),
 * then hands the bound inputs + file grants to the parent to start the run.
 */
const props = defineProps<{
  open: boolean
  workflowTitle: string
  nodeCount: number
  inputSchemaText: string
  busy?: boolean
}>()
const inputsText = defineModel<string>('inputsText', { required: true })
const emit = defineEmits<{
  close: []
  run: [payload: { inputs: Record<string, unknown>; permissionMode: AiPermissionMode; files: AgentRunFile[] }]
}>()

const { t } = useI18n()
const permissionMode = ref<AiPermissionMode>('ask-for-approval')

const schema = computed(() => parseWorkflowSchema(props.inputSchemaText))
const schemaFields = computed(() => Object.entries(schema.value.properties ?? {}))
const requiredInputs = computed(() => new Set(schema.value.required ?? []))
const runInputs = computed(() => parseWorkflowArguments(inputsText.value) ?? {})

// ── run-form file inputs + dynamic option sources ───────────────────────
/** Per-input grants from the run dialog's file pickers (POST /api/ai/files/upload). */
const runFileRefs = ref<Record<string, ActiveFileEntry[]>>({})
/** Display names of the picked files, so the form can show what was chosen. */
const runFileNames = ref<Record<string, string>>({})
/** Options fetched from plugin list tools for `x-fengyu-enum` inputs. */
const enumOptions = ref<Record<string, Array<{ value: unknown; label: string }>>>({})
const enumLoading = ref<Record<string, boolean>>({})
const enumError = ref<Record<string, string | null>>({})
const runFileError = ref<Record<string, string | null>>({})
/** Sheet → header columns of the picked workbook, filled by the automatic excel_analyze. */
const workbookAnalysis = ref<Record<string, string[]>>({})
const workbookAnalyzing = ref(false)
const workbookAnalysisError = ref<string | null>(null)

/** Inputs whose value is a host-managed shared scratch directory (no user interaction). */
const autoSharedDirInputs = computed(() => schemaFields.value
  .filter(([, property]) => property['x-fengyu-auto'] === 'shared-directory')
  .map(([name]) => name))

const missingRunInputs = computed(() =>
  (schema.value.required ?? []).filter((name) => !isWorkflowValueConfigured(runInputs.value[name])))
const missingRunInputLabels = computed(() => {
  const properties = schema.value.properties ?? {}
  return missingRunInputs.value.map((name) => properties[name]?.title || humanizeWorkflowField(name))
})

function resetDialogState() {
  runFileRefs.value = {}
  runFileNames.value = {}
  enumOptions.value = {}
  enumLoading.value = {}
  enumError.value = {}
  runFileError.value = {}
  workbookAnalysis.value = {}
  workbookAnalysisError.value = null
}

function setInputRaw(name: string, value: unknown) {
  const next = { ...runInputs.value, [name]: value }
  inputsText.value = JSON.stringify(next, null, 2)
}

/** Seeds defaults and shared-dir placeholders, and starts dynamic option loads. */
function prepare() {
  for (const [name, property] of schemaFields.value) {
    if (property['x-fengyu-auto'] === 'shared-directory') {
      setInputRaw(name, `@file:${name}`)
      continue
    }
    if ('default' in property && property.default !== undefined
      && !isWorkflowValueConfigured(runInputs.value[name])) {
      setInputRaw(name, property.default)
    }
    const source = property['x-fengyu-enum']
    if (source) void loadEnumOptions(name, source)
  }
}

watch(() => props.open, (open) => {
  if (open) {
    resetDialogState()
    prepare()
  }
})

async function pickRunFile(name: string, event: Event) {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  input.value = ''
  if (!file) return
  runFileError.value = { ...runFileError.value, [name]: null }
  try {
    const refs = await api.uploadAiFile(file)
    runFileRefs.value = { ...runFileRefs.value, [name]: refs }
    runFileNames.value = { ...runFileNames.value, [name]: file.name }
    setInputRaw(name, `@file:${name}`)
    if (schema.value.properties?.[name]?.['x-fengyu-analyze'] === 'excel') {
      void analyzeWorkbook(refs)
    }
  } catch (e) {
    runFileError.value = { ...runFileError.value, [name]: e instanceof Error ? e.message : t('agent.failed') }
  }
}

/**
 * Analyzes the just-picked workbook through the Excel plugin's own copy of the grant, so
 * the run form's sheet/column fields become datalist candidates instead of blind typing.
 * Failures never block the run — the fields stay free-text.
 */
async function analyzeWorkbook(refs: ActiveFileEntry[]) {
  const excelRef = refs.find((entry) => entry.pluginId === 'fan.summer.excel')
  if (!excelRef) return
  workbookAnalyzing.value = true
  workbookAnalysisError.value = null
  try {
    const result = await api.invokePluginMethod<{
      success?: boolean
      summary?: string
      sheets?: Record<string, Record<string, string>>
    }>('fan.summer.excel', 'excel_analyze', { filePath: excelRef.ref })
    const sheets: Record<string, string[]> = {}
    for (const [sheet, columns] of Object.entries(result?.sheets ?? {})) {
      sheets[sheet] = Object.values(columns ?? {})
    }
    workbookAnalysis.value = sheets
  } catch (e) {
    workbookAnalysis.value = {}
    workbookAnalysisError.value = e instanceof Error ? e.message : t('agent.failed')
  } finally {
    workbookAnalyzing.value = false
  }
}

/** Option candidates for a field annotated with `x-fengyu-options-from`. */
function optionsFromSource(source: string | undefined, rowSheet?: unknown): string[] {
  if (source === 'workbook-sheets') return Object.keys(workbookAnalysis.value)
  if (source === 'workbook-columns') {
    const sheet = typeof rowSheet === 'string' ? rowSheet : ''
    const columns = sheet ? workbookAnalysis.value[sheet] : undefined
    // A row whose sheet is not (yet) picked still sees the union, so the user can
    // pre-fill a column and the sheet name after.
    return columns ?? [...new Set(Object.values(workbookAnalysis.value).flat())]
  }
  return []
}

function clearRunFile(name: string) {
  const nextRefs = { ...runFileRefs.value }
  delete nextRefs[name]
  runFileRefs.value = nextRefs
  const nextNames = { ...runFileNames.value }
  delete nextNames[name]
  runFileNames.value = nextNames
  setInputRaw(name, '')
}

async function loadEnumOptions(name: string, source: WorkflowEnumSource) {
  if (enumLoading.value[name] || enumOptions.value[name]) return
  enumLoading.value = { ...enumLoading.value, [name]: true }
  enumError.value = { ...enumError.value, [name]: null }
  try {
    const result = await api.invokePluginMethod<Record<string, unknown>>(source.plugin, source.method)
    const list = Array.isArray(result?.[source.items])
      ? result[source.items] as Array<Record<string, unknown>>
      : []
    enumOptions.value = {
      ...enumOptions.value,
      [name]: list.map((item) => ({
        value: item[source.value],
        label: [item[source.label], source.labelSecondary ? item[source.labelSecondary] : undefined]
          .filter((part) => part !== undefined && part !== null && part !== '')
          .join(' · '),
      })),
    }
  } catch (e) {
    enumError.value = { ...enumError.value, [name]: e instanceof Error ? e.message : t('agent.failed') }
  } finally {
    enumLoading.value = { ...enumLoading.value, [name]: false }
  }
}

function enumOptionSelected(name: string, value: unknown): boolean {
  const current = runInputs.value[name]
  return Array.isArray(current) ? current.some((item) => String(item) === String(value))
    : String(current) === String(value)
}

function toggleEnumOption(name: string, value: unknown) {
  const current = runInputs.value[name]
  const list = Array.isArray(current) ? current : []
  const next = enumOptionSelected(name, value)
    ? list.filter((item) => String(item) !== String(value))
    : [...list, value]
  setInputRaw(name, next)
}

function selectEnumOption(name: string, event: Event) {
  const value = (event.target as HTMLSelectElement).value
  const option = enumOptions.value[name]?.find((item) => String(item.value) === value)
  setInputRaw(name, option ? option.value : value)
}

// ── run-form array-of-object row editor (schema.items.properties driven) ──

function runArrayRows(name: string): Record<string, unknown>[] {
  const value = runInputs.value[name]
  return Array.isArray(value)
    ? value.filter((row) => row && typeof row === 'object' && !Array.isArray(row)) as Record<string, unknown>[]
    : []
}

function writeRunArrayRows(name: string, rows: Record<string, unknown>[]) {
  setInputRaw(name, rows)
}

function updateRunArrayField(name: string, index: number, field: string, value: unknown) {
  const rows = runArrayRows(name).map((row) => ({ ...row }))
  if (!rows[index]) return
  rows[index] = { ...rows[index], [field]: value }
  writeRunArrayRows(name, rows)
}

function addRunArrayRow(name: string) {
  writeRunArrayRows(name, [...runArrayRows(name), {}])
}

function removeRunArrayRow(name: string, index: number) {
  writeRunArrayRows(name, runArrayRows(name).filter((_, i) => i !== index))
}

function updateRunArrayFieldFromEvent(name: string, index: number, field: string, event: Event) {
  updateRunArrayField(name, index, field, (event.target as HTMLInputElement).value)
}

// ── simple typed input editors ───────────────────────────────────────────

interface InputSchema {
  type?: string
  enum?: unknown[]
  items?: InputSchema
}

function workflowInputValue(name: string): unknown {
  return runInputs.value[name] ?? ''
}

function displayWorkflowInputValue(name: string, property: WorkflowSchemaProperty): string | number {
  const value = workflowInputValue(name)
  if (property.type === 'array') return Array.isArray(value) ? value.join(', ') : String(value ?? '')
  if (property.type === 'object') return JSON.stringify(value || {}, null, 2)
  return typeof value === 'number' ? value : String(value ?? '')
}

function valueFromInput(property: InputSchema, event: Event): unknown {
  const target = event.target as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
  if (property.type === 'boolean' && target instanceof HTMLInputElement) return target.checked
  if (property.type === 'integer' || property.type === 'number') {
    // Number('') === 0: clearing the field removes the key instead of writing a 0.
    if (target.value === '') return undefined
    const parsed = Number(target.value)
    return Number.isFinite(parsed) ? parsed : 0
  }
  if (property.enum?.length) return property.enum.find((option) => String(option) === target.value) ?? target.value
  return target.value
}

function setWorkflowInputValue(name: string, property: WorkflowSchemaProperty, event: Event) {
  const target = event.target as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
  let value: unknown
  if (property.type === 'array') {
    const items = target.value.split(/[,\n]/).map((item) => item.trim()).filter(Boolean)
    value = property.items?.type === 'integer' || property.items?.type === 'number' ? items.map(Number) : items
  } else if (property.type === 'object') {
    try {
      value = JSON.parse(target.value || '{}')
    } catch {
      return
    }
  } else {
    value = valueFromInput(property, event)
  }
  setInputRaw(name, value)
}

function startRun() {
  // File-class inputs: picked-file grants travel with the run; auto shared dirs are
  // minted server-side. Args already carry the matching @file:<name> placeholders.
  const files: AgentRunFile[] = Object.entries(runFileRefs.value).map(([name, refs]) => ({ name, refs }))
  for (const name of autoSharedDirInputs.value) {
    files.push({ name, createSharedDirectory: true })
  }
  emit('run', {
    inputs: parseWorkflowArguments(inputsText.value) ?? {},
    permissionMode: permissionMode.value,
    files,
  })
}
</script>

<template>
  <div v-if="open" class="flow-run-backdrop" @click.self="emit('close')">
    <section class="flow-run-dialog" role="dialog" aria-modal="true">
      <div class="flow-run-dialog__icon"><i class="mdi mdi-play" /></div>
      <div class="flow-run-dialog__heading">
        <h2>{{ t('agent.testRun') }}</h2>
        <p>{{ workflowTitle }} · {{ nodeCount }} {{ t('agent.nodes') }}</p>
      </div>
      <button class="cx-iconbtn cx-iconbtn--sm flow-run-dialog__close" :aria-label="t('flows.close')" @click="emit('close')"><i class="mdi mdi-close" /></button>

      <div v-if="schemaFields.length" class="flow-run-form">
        <label v-for="([name, property]) in schemaFields" :key="name" class="flow-field">
          <span>{{ property.title || humanizeWorkflowField(name) }} <em v-if="requiredInputs.has(name)">*</em></span>
          <small v-if="property.description">{{ property.description }}</small>

          <span v-if="property.format === 'fengyu-file'" class="flow-file-input">
            <label
              :for="`run-file-${name}`"
              class="cx-btn cx-btn--outline flow-file-label"
              :class="{ 'flow-file-label--disabled': busy }"
            ><i class="mdi mdi-paperclip" /> {{ runFileNames[name] || t('agent.chooseFile') }}</label>
            <input
              :id="`run-file-${name}`"
              type="file"
              class="flow-file-native"
              :disabled="busy"
              @change="pickRunFile(name, $event)"
            >
            <button
              v-if="runFileRefs[name]"
              class="cx-iconbtn cx-iconbtn--sm"
              :title="t('agent.clearFile')"
              :disabled="busy"
              @click.prevent="clearRunFile(name)"
            ><i class="mdi mdi-close" /></button>
            <small v-if="runFileRefs[name]" class="flow-file-chosen">
              <i class="mdi mdi-check-circle-outline" /> {{ runFileNames[name] }}
            </small>
            <small v-if="workbookAnalyzing && property['x-fengyu-analyze'] === 'excel'" class="cx-muted flow-file-chosen">
              <span class="cx-spin" /> {{ t('agent.analyzingWorkbook') }}
            </small>
            <small v-if="workbookAnalysisError && property['x-fengyu-analyze'] === 'excel'" class="flow-file-error">
              {{ t('agent.analyzeFailed') }}: {{ workbookAnalysisError }}
            </small>
            <small v-if="runFileError[name]" class="flow-file-error">{{ runFileError[name] }}</small>
          </span>

          <span v-else-if="property['x-fengyu-auto'] === 'shared-directory'" class="flow-auto-dir">
            <i class="mdi mdi-folder-sync-outline" />
            <span>{{ t('agent.autoSharedDir') }}</span>
          </span>

          <template v-else-if="property['x-fengyu-enum']">
            <span v-if="enumLoading[name]" class="cx-muted flow-enum-status">
              <span class="cx-spin" /> {{ t('agent.loadingOptions') }}
            </span>
            <template v-else-if="enumOptions[name]?.length">
              <select
                v-if="!property['x-fengyu-enum'].multiple"
                class="cx-input"
                :value="String(workflowInputValue(name) ?? '')"
                :disabled="busy"
                @change="selectEnumOption(name, $event)"
              >
                <option value="">{{ t('agent.notSet') }}</option>
                <option
                  v-for="option in enumOptions[name]"
                  :key="String(option.value)"
                  :value="String(option.value)"
                >{{ option.label || String(option.value) }}</option>
              </select>
              <div v-else class="flow-enum-list">
                <label v-for="option in enumOptions[name]" :key="String(option.value)">
                  <input
                    type="checkbox"
                    :checked="enumOptionSelected(name, option.value)"
                    :disabled="busy"
                    @change="toggleEnumOption(name, option.value)"
                  >
                  <span>{{ option.label || String(option.value) }}</span>
                </label>
              </div>
            </template>
            <template v-else>
              <small v-if="enumError[name]" class="flow-file-error">{{ enumError[name] }}</small>
              <small v-else-if="property['x-fengyu-enum']?.plugin === 'fan.summer.email'" class="cx-muted">
                {{ t('agent.enumEmailHint') }}
              </small>
              <small v-else class="cx-muted">{{ t('agent.noOptions') }}</small>
              <input
                class="cx-input"
                type="text"
                :value="displayWorkflowInputValue(name, property)"
                :disabled="busy"
                :placeholder="t('agent.enterValue')"
                @input="setWorkflowInputValue(name, property, $event)"
              >
            </template>
          </template>

          <div v-else-if="property.type === 'array' && property.items?.type === 'object' && property.items.properties" class="flow-rules-editor">
            <span v-if="workbookAnalyzing" class="cx-muted flow-enum-status">
              <span class="cx-spin" /> {{ t('agent.analyzingWorkbook') }}
            </span>
            <div v-for="(row, index) in runArrayRows(name)" :key="index" class="flow-rule-row">
              <div class="flow-rule-row__head">
                <strong>{{ t('agent.ruleRow', { n: index + 1 }) }}</strong>
                <button
                  class="cx-iconbtn cx-iconbtn--sm"
                  :title="t('agent.removeRule')"
                  :disabled="busy"
                  @click.prevent="removeRunArrayRow(name, index)"
                ><i class="mdi mdi-delete-outline" /></button>
              </div>
              <label v-for="([fieldName, fieldSchema]) in Object.entries(property.items.properties)" :key="fieldName">
                <span>{{ fieldSchema.title || humanizeWorkflowField(fieldName) }}</span>
                <input
                  class="cx-input"
                  type="text"
                  :value="String(row[fieldName] ?? '')"
                  :list="optionsFromSource(fieldSchema['x-fengyu-options-from'], row.sheetName).length ? `dl-${name}-${fieldName}` : undefined"
                  :placeholder="fieldSchema.description || t('agent.enterValue')"
                  :disabled="busy"
                  @input="updateRunArrayFieldFromEvent(name, index, fieldName, $event)"
                >
                <datalist
                  v-if="optionsFromSource(fieldSchema['x-fengyu-options-from'], row.sheetName).length"
                  :id="`dl-${name}-${fieldName}`"
                >
                  <option
                    v-for="option in optionsFromSource(fieldSchema['x-fengyu-options-from'], row.sheetName)"
                    :key="option"
                    :value="option"
                  />
                </datalist>
              </label>
            </div>
            <button class="flow-add-item" :disabled="busy" @click.prevent="addRunArrayRow(name)">
              <i class="mdi mdi-plus" /> {{ t('agent.addRule') }}
            </button>
          </div>

          <label v-else-if="property.type === 'boolean'" class="flow-boolean-input"><input type="checkbox" :checked="Boolean(workflowInputValue(name))" :disabled="busy" @change="setWorkflowInputValue(name, property, $event)"><span>{{ t('agent.enabled') }}</span></label>
          <textarea v-else-if="property.type === 'array' || property.type === 'object'" class="cx-textarea" rows="3" :value="displayWorkflowInputValue(name, property)" :placeholder="property.type === 'array' ? t('agent.arrayInputPlaceholder') : t('agent.objectInputPlaceholder')" :disabled="busy" @change="setWorkflowInputValue(name, property, $event)" />
          <template v-else>
            <input
              class="cx-input"
              :type="property.type === 'integer' || property.type === 'number' ? 'number' : 'text'"
              :value="displayWorkflowInputValue(name, property)"
              :list="optionsFromSource(property['x-fengyu-options-from']).length ? `dl-${name}` : undefined"
              :placeholder="property.description || t('agent.enterValue')"
              :disabled="busy"
              @input="setWorkflowInputValue(name, property, $event)"
            >
            <datalist v-if="optionsFromSource(property['x-fengyu-options-from']).length" :id="`dl-${name}`">
              <option
                v-for="option in optionsFromSource(property['x-fengyu-options-from'])"
                :key="option"
                :value="option"
              />
            </datalist>
          </template>
        </label>
      </div>
      <div v-else class="cx-muted flow-config-empty">{{ t('agent.noRunInputs') }}</div>

      <label class="flow-field"><span>{{ t('agent.permissionMode') }}</span><select v-model="permissionMode" class="cx-select" :disabled="busy"><option value="ask-for-approval">{{ t('aichat.permissionAsk') }}</option><option value="approve-for-me">{{ t('aichat.permissionAuto') }}</option><option value="full-access">{{ t('aichat.permissionFullAccess') }}</option></select></label>
      <small class="cx-muted">{{ t('agent.runInputsHint') }}</small>
      <details class="flow-advanced"><summary>{{ t('agent.advancedJsonInput') }}</summary><div class="flow-advanced__body"><textarea v-model="inputsText" class="cx-textarea mono" rows="6" :disabled="busy" /></div></details>
      <div v-if="missingRunInputs.length" class="cx-alert cx-alert--error"><span class="cx-alert__body">{{ t('agent.missingRunInputs', { names: missingRunInputLabels.join(', ') }) }}</span></div>
      <div class="flow-run-dialog__actions">
        <button class="cx-btn cx-btn--outline" @click="emit('close')">{{ t('common.cancel') }}</button>
        <button class="flow-run-button" :disabled="busy || !!missingRunInputs.length" @click="startRun"><i class="mdi mdi-play" /> {{ t('agent.startRun') }}</button>
      </div>
    </section>
  </div>
</template>

<style scoped>
.flow-run-backdrop {
  position: fixed;
  z-index: 1000;
  inset: 0;
  display: grid;
  place-items: center;
  padding: 20px;
  background: rgba(0, 0, 0, .48);
  backdrop-filter: blur(3px);
}

.flow-run-dialog {
  position: relative;
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 14px;
  width: min(560px, 100%);
  max-height: calc(100vh - 40px);
  padding: 22px;
  border: 1px solid rgb(var(--v-theme-outline-variant));
  border-radius: 14px;
  background: rgb(var(--v-theme-surface));
  box-shadow: 0 24px 72px rgba(0, 0, 0, .35);
  overflow-y: auto;
}

.flow-run-dialog__icon {
  display: grid;
  place-items: center;
  flex: 0 0 auto;
  width: 34px;
  height: 34px;
  color: rgb(var(--v-theme-primary));
  border-radius: 10px;
  background: rgba(var(--v-theme-primary), .12);
}

.flow-run-dialog__heading h2 { margin: 0 0 2px; font-size: 18px; }
.flow-run-dialog__heading p { margin: 0; color: rgba(var(--v-theme-on-surface), .58); font-size: 11px; }
.flow-run-dialog__close { position: absolute; top: 14px; right: 14px; }
.flow-run-dialog > .flow-field,
.flow-run-dialog > .flow-run-form,
.flow-run-dialog > .cx-alert,
.flow-run-dialog > small,
.flow-run-dialog > .flow-advanced,
.flow-run-dialog__actions { grid-column: 1 / -1; }

.flow-run-form { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
.flow-field { display: block; margin-bottom: 14px; }
.flow-field > span { display: block; margin-bottom: 6px; color: rgba(var(--v-theme-on-surface), .68); font-size: 11px; }
.flow-field > small { display: block; margin: -2px 0 5px; color: rgba(var(--v-theme-on-surface), .55); font-size: 9px; }
.flow-field em { color: rgb(var(--v-theme-error)); font-style: normal; }
.flow-run-form .flow-field { margin: 0; }

.flow-run-button {
  display: inline-flex;
  gap: 6px;
  align-items: center;
  justify-content: center;
  min-height: 34px;
  padding: 6px 14px;
  color: rgb(var(--v-theme-on-primary));
  font: inherit;
  font-size: 12px;
  font-weight: 650;
  border: 0;
  border-radius: 8px;
  background: rgb(var(--v-theme-primary));
  box-shadow: 0 4px 12px rgba(var(--v-theme-primary), .2);
  cursor: pointer;
}

.flow-run-button:disabled { opacity: .45; cursor: not-allowed; }
.flow-run-dialog__actions { display: flex; gap: 8px; justify-content: flex-end; }
.flow-run-dialog .cx-select { width: 100%; }

.flow-config-empty {
  padding: 10px;
  font-size: 11px;
  border: 1px dashed rgb(var(--v-theme-outline-variant));
  border-radius: 8px;
}

.flow-advanced { margin-bottom: 14px; }
.flow-advanced summary { padding: 10px 0; color: rgba(var(--v-theme-on-surface), .68); font-size: 11px; cursor: pointer; }
.flow-advanced__body { padding-top: 3px; }
.flow-advanced .cx-textarea { width: 100%; resize: vertical; font-size: 11px; }

.flow-boolean-input { display: flex; gap: 7px; align-items: center; min-height: 30px; font-size: 11px; }

/* file picker / auto shared dir / dynamic enum options */
.flow-file-input { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; }
.flow-file-native { position: absolute; width: 1px; height: 1px; opacity: 0; overflow: hidden; }
.flow-file-label { cursor: pointer; text-align: center; }
.flow-file-label--disabled { opacity: .55; pointer-events: none; }
.flow-file-chosen { display: inline-flex; align-items: center; gap: 4px; color: rgb(var(--v-theme-success)); font-size: 10px; }
.flow-file-error { width: 100%; color: rgb(var(--v-theme-error)); font-size: 10px; }
.flow-auto-dir { display: flex; align-items: center; gap: 7px; padding: 8px 10px; border: 1px dashed rgb(var(--v-theme-outline-variant)); border-radius: 8px; color: rgba(var(--v-theme-on-surface), .68); font-size: 11px; }
.flow-enum-status { display: inline-flex; align-items: center; gap: 7px; font-size: 11px; }
.flow-enum-list { display: grid; gap: 3px; max-height: 150px; overflow-y: auto; padding: 6px 8px; border: 1px solid rgb(var(--v-theme-outline-variant)); border-radius: 8px; }
.flow-enum-list label { display: flex; align-items: center; gap: 7px; font-size: 11px; cursor: pointer; }

/* array-of-object row editor (multi-rule split configuration) */
.flow-rules-editor { display: grid; gap: 7px; }
.flow-rule-row { display: grid; gap: 5px; padding: 8px 9px; border: 1px solid rgb(var(--v-theme-outline-variant)); border-radius: 9px; background: rgb(var(--v-theme-surface-container)); }
.flow-rule-row__head { display: flex; align-items: center; justify-content: space-between; }
.flow-rule-row__head strong { font-size: 10px; color: rgba(var(--v-theme-on-surface), .6); }
.flow-rule-row label { display: grid; gap: 3px; font-size: 10px; color: rgba(var(--v-theme-on-surface), .7); }
.flow-rule-row .cx-input { font-size: 12px; }
.flow-add-item { display: inline-flex; gap: 5px; align-items: center; justify-content: center; padding: 6px 8px; color: rgb(var(--v-theme-primary)); font: inherit; font-size: 10px; border: 1px dashed rgba(var(--v-theme-primary), .6); border-radius: 7px; background: rgba(var(--v-theme-primary), .05); cursor: pointer; }

@media (max-width: 850px) {
  .flow-run-form { grid-template-columns: 1fr; }
}
</style>

// frontend/src/components/flow/FlowRunDialog.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { AlertCircle, CheckCircle2, FileSearch, FolderSearch, Loader2, Play, Square, X } from 'lucide-react'
import type { ActiveFileEntry, AgentRunFile, AiPermissionMode } from '@/services/types'
import { services } from '@/services'
import { getPlatform } from '@/platform'
import type { AgentRunStreamState } from '@/lib/agentRunStream'
import { humanizeWorkflowField } from '@/lib/flowDisplay'
import { parseJsonObject } from '@/lib/flowGraph'
import { createRunFileGrantLedger } from '@/lib/runFileGrantLedger'

/**
 * Flow run dialog (modal): renders the workflow's input schema as a friendly
 * form — file-class inputs become pickers whose grants travel with the run
 * (`@file:<name>` placeholders in args, per-plugin refs under `files`) — then
 * starts the run and shows the live plan-execute stream or the error state.
 */

type InputValue = string | number | boolean | Record<string, unknown> | unknown[] | undefined

export interface FlowRunStartPayload {
  inputs: Record<string, unknown>
  permissionMode: AiPermissionMode
  /** File-class input grants minted by this dialog's pickers. */
  files?: AgentRunFile[]
}

interface SchemaProperty {
  type?: string
  title?: string
  description?: string
  enum?: unknown[]
  default?: unknown
  format?: string
  'x-fengyu-file-access'?: 'read' | 'read-write'
}

export function FlowRunDialog(props: {
  open: boolean
  workflowTitle: string
  nodeCount: number
  inputSchemaText: string
  /** Live run stream state; null while no run has been started from this dialog. */
  run: AgentRunStreamState | null
  onClose: () => void
  onRun: (payload: FlowRunStartPayload) => void
  onCancel: () => void
  onApprove: () => void
}) {
  const { t } = useTranslation()
  const [values, setValues] = useState<Record<string, InputValue>>({})
  const [permissionMode, setPermissionMode] = useState<AiPermissionMode>('ask-for-approval')
  /** Picked-file grants per input name (dialog-owned until the run takes them). */
  const [fileRefs, setFileRefs] = useState<Record<string, ActiveFileEntry[]>>({})
  const [fileNames, setFileNames] = useState<Record<string, string>>({})
  const [fileErrors, setFileErrors] = useState<Record<string, string | null>>({})
  /** Ledger session id — pickers capture it at pick start, accept() guards staleness. */
  const [grantSession, setGrantSession] = useState(0)
  const ledgerRef = useRef<ReturnType<typeof createRunFileGrantLedger> | null>(null)
  const ledger = useMemo(() => ledgerRef.current ?? (ledgerRef.current = createRunFileGrantLedger((entry) => {
    void services.chat.revokeAiFile(entry.pluginId, entry.ref.id).catch(() => {
      // Revocation is best-effort cleanup; the host reaps orphans eventually.
    })
  })), [])

  const fields = useMemo(() => {
    const schema = parseJsonObject(props.inputSchemaText)
    const properties = (schema?.properties ?? {}) as Record<string, SchemaProperty>
    const required = new Set(Array.isArray(schema?.required) ? (schema.required as string[]) : [])
    return Object.entries(properties).map(([name, property]) => ({
      name,
      property,
      required: required.has(name),
    }))
  }, [props.inputSchemaText])

  // Seed defaults each time the dialog opens fresh (no run in flight); a fresh
  // open also resets grant ownership — earlier unsubmitted picks are revoked.
  useEffect(() => {
    if (!props.open || props.run) return
    setGrantSession(ledger.beginSession())
    setFileRefs({})
    setFileNames({})
    setFileErrors({})
    const seeded: Record<string, InputValue> = {}
    for (const field of fields) {
      const property = field.property
      if (property.default !== undefined && property.default !== null) {
        seeded[field.name] = property.default as InputValue
      } else if (property.type === 'boolean') {
        seeded[field.name] = false
      } else {
        seeded[field.name] = ''
      }
    }
    setValues(seeded)
    // The ledger is a ref-mounted singleton; re-seeding is keyed by open/run/fields.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.open, props.run, fields])

  const closeRef = useRef(props.onClose)
  closeRef.current = props.onClose

  useEffect(() => {
    if (!props.open) return
    const onKeydown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        event.stopPropagation()
        closeRef.current()
      }
    }
    window.addEventListener('keydown', onKeydown, true)
    return () => window.removeEventListener('keydown', onKeydown, true)
  }, [props.open])

  // Close/unmount without submitting: still-owned grants go back (the captured
  // props.run reflects the submit state at mount — ownership tracking is the
  // ledger's job, not this effect's deps).
  useEffect(() => () => {
    if (!props.run) ledger.releaseRemaining()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  if (!props.open) return null

  const showStream = props.run !== null
  const missing = fields
    .filter((field) => field.required && !isConfigured(values[field.name]))
    .map((field) => field.property.title || humanizeWorkflowField(field.name))

  const setFileValue = (name: string, refs: ActiveFileEntry[] | null, displayName: string | undefined,
    sessionAtStart: number) => {
    if (refs === null) {
      ledger.clear(name)
      setFileRefs((current) => { const next = { ...current }; delete next[name]; return next })
      setFileNames((current) => { const next = { ...current }; delete next[name]; return next })
      setValues((current) => ({ ...current, [name]: '' }))
      return
    }
    // A pick resolving after the dialog reopened (or after submit) hands its
    // grants straight back — the form state stays untouched.
    if (!ledger.accept(sessionAtStart, name, refs)) return
    setFileRefs((current) => ({ ...current, [name]: refs }))
    if (displayName) setFileNames((current) => ({ ...current, [name]: displayName }))
    setValues((current) => ({ ...current, [name]: `@file:${name}` }))
  }

  const startRun = () => {
    // File-class inputs: picked-file grants travel with the run. Ownership
    // leaves the dialog with this submit — the created run's terminal cleanup
    // now owns every revoke.
    const files: AgentRunFile[] = Object.entries(fileRefs).map(([name, refs]) => ({ name, refs }))
    ledger.markTransferred()
    props.onRun({
      inputs: Object.fromEntries(Object.entries(values)
        .filter(([, value]) => isConfigured(value))),
      permissionMode,
      files,
    })
  }

  return (
    <div className="flow-modal-backdrop" role="presentation" onClick={props.onClose}>
      <section
        className="flow-run-dialog"
        role="dialog"
        aria-modal="true"
        aria-label={t('agent.testRun')}
        onClick={(event) => event.stopPropagation()}
      >
        <div className="flow-run-dialog__icon"><Play size={16} /></div>
        <div className="flow-run-dialog__heading">
          <h2>{showStream ? t('agent.runPanel') : t('agent.testRun')}</h2>
          <p>{props.workflowTitle} · {props.nodeCount} {t('agent.nodes')}</p>
        </div>
        <button className="cx-iconbtn cx-iconbtn--sm flow-run-dialog__close" aria-label={t('flows.close')} onClick={props.onClose}>
          <X size={16} />
        </button>

        {showStream ? (
          <RunStream run={props.run!} onCancel={props.onCancel} onClose={props.onClose} onApprove={props.onApprove} />
        ) : (
          <>
            {fields.length ? (
              <div className="flow-run-form">
                {fields.map(({ name, property, required }) => (
                  <label key={name} className="flow-field">
                    <span>
                      {property.title || humanizeWorkflowField(name)}
                      {required ? <em> *</em> : null}
                    </span>
                    {property.description ? <small>{property.description}</small> : null}
                    <RunInput
                      name={name}
                      property={property}
                      value={values[name]}
                      pickedName={fileNames[name]}
                      error={fileErrors[name] ?? null}
                      grantSession={grantSession}
                      onChange={(value) => setValues((current) => ({ ...current, [name]: value }))}
                      onPick={(refs, displayName, sessionAtStart) =>
                        setFileValue(name, refs, displayName, sessionAtStart)}
                      onClear={() => setFileValue(name, null, undefined, ledger.session())}
                      onError={(message) => setFileErrors((current) => ({ ...current, [name]: message }))}
                    />
                  </label>
                ))}
              </div>
            ) : (
              <div className="cx-muted flow-config-empty">{t('agent.noRunInputs')}</div>
            )}

            <label className="flow-field">
              <span>{t('agent.permissionMode')}</span>
              <select
                className="cx-select"
                value={permissionMode}
                onChange={(event) => setPermissionMode(event.target.value as AiPermissionMode)}
              >
                <option value="ask-for-approval">{t('aichat.permissionAsk')}</option>
                <option value="approve-for-me">{t('aichat.permissionAuto')}</option>
                <option value="full-access">{t('aichat.permissionFullAccess')}</option>
              </select>
            </label>
            <small className="cx-muted">{t('agent.runInputsHint')}</small>
            {missing.length > 0 && (
              <div className="cx-alert cx-alert--error">
                <span className="cx-alert__body">{t('agent.missingRunInputs', { names: missing.join(', ') })}</span>
              </div>
            )}
            <div className="flow-run-dialog__actions">
              <button className="cx-btn cx-btn--outline" onClick={props.onClose}>{t('common.cancel')}</button>
              <button
                className="flow-run-button"
                disabled={missing.length > 0}
                onClick={startRun}
              >
                <Play size={14} /> {t('agent.startRun')}
              </button>
            </div>
          </>
        )}
      </section>
    </div>
  )
}

function isConfigured(value: InputValue): boolean {
  if (value === undefined || value === null) return false
  if (typeof value === 'string') return value.trim().length > 0
  if (Array.isArray(value)) return value.length > 0
  if (typeof value === 'object') return Object.keys(value as Record<string, unknown>).length > 0
  return true
}

function RunInput(props: {
  name: string
  property: SchemaProperty
  value: InputValue
  /** Display name of the picked file/directory (grant-backed inputs). */
  pickedName?: string
  error: string | null
  /** Ledger session id at render time — captured by pickers at pick start. */
  grantSession: number
  onChange: (value: InputValue) => void
  onPick: (refs: ActiveFileEntry[] | null, displayName: string | undefined, sessionAtStart: number) => void
  onClear: () => void
  onError: (message: string | null) => void
}) {
  const { t } = useTranslation()
  const { property } = props
  const type = property.type
  if (property.format === 'fengyu-file' || property.format === 'fengyu-directory') {
    return (
      <FileRunInput
        name={props.name}
        directory={property.format === 'fengyu-directory'}
        writable={property['x-fengyu-file-access'] === 'read-write'}
        picked={typeof props.value === 'string' && props.value.startsWith('@file:')}
        pickedName={props.pickedName}
        error={props.error}
        grantSession={props.grantSession}
        onPick={props.onPick}
        onClear={props.onClear}
        onError={props.onError}
      />
    )
  }
  if (type === 'boolean') {
    return (
      <label className="flow-boolean-input">
        <input
          type="checkbox"
          checked={Boolean(props.value)}
          onChange={(event) => props.onChange(event.target.checked)}
        />
        <span>{t('agent.enabled')}</span>
      </label>
    )
  }
  if (type === 'object' || type === 'array') {
    return (
      <textarea
        className="cx-textarea mono"
        rows={3}
        placeholder={type === 'array' ? t('agent.arrayInputPlaceholder') : t('agent.objectInputPlaceholder')}
        value={typeof props.value === 'string' ? props.value : JSON.stringify(props.value ?? (type === 'array' ? [] : {}), null, 2)}
        onChange={(event) => props.onChange(event.target.value)}
        onBlur={(event) => {
          try {
            props.onChange(JSON.parse(event.target.value || (type === 'array' ? '[]' : '{}')))
          } catch {
            /* keep the raw text until it parses */
          }
        }}
      />
    )
  }
  if (property.enum?.length) {
    return (
      <select
        className="cx-select"
        value={String(props.value ?? '')}
        onChange={(event) => {
          const raw = event.target.value
          let match: InputValue | undefined
          if (property.enum) {
            match = property.enum.find((option) => String(option) === raw) as InputValue | undefined
          }
          props.onChange(match !== undefined ? match : raw)
        }}
      >
        <option value="">{t('agent.notSet')}</option>
        {property.enum.map((option) => (
          <option key={String(option)} value={String(option)}>{String(option)}</option>
        ))}
      </select>
    )
  }
  return (
    <input
      className="cx-input"
      type={type === 'number' || type === 'integer' ? 'number' : 'text'}
      placeholder={property.description || t('agent.enterValue')}
      value={props.value === undefined || props.value === null || typeof props.value === 'object'
        ? ''
        : String(props.value)}
      onChange={(event) => {
        if (type === 'number' || type === 'integer') {
          props.onChange(event.target.value === '' ? undefined : Number(event.target.value))
        } else {
          props.onChange(event.target.value)
        }
      }}
    />
  )
}

/**
 * File-class run input: a picker that mints grants. Desktop dialogs return
 * native paths granted via /api/ai/files/native; the web falls back to uploads
 * (webkitdirectory for directories). Grants are dialog-owned until submit.
 */
function FileRunInput(props: {
  name: string
  directory: boolean
  writable: boolean
  picked: boolean
  pickedName?: string
  error: string | null
  grantSession: number
  onPick: (refs: ActiveFileEntry[] | null, displayName: string | undefined, sessionAtStart: number) => void
  onClear: () => void
  onError: (message: string | null) => void
}) {
  const { t } = useTranslation()
  const [busy, setBusy] = useState(false)
  const fileInputRef = useRef<HTMLInputElement | null>(null)

  const storeDirectory = async (refsPromise: Promise<ActiveFileEntry[]>, displayName: string) => {
    const sessionAtStart = props.grantSession
    setBusy(true)
    props.onError(null)
    try {
      const refs = await refsPromise
      if (!refs.length) throw new Error(t('aichat.fileNeedsPlugin'))
      props.onPick(refs, displayName, sessionAtStart)
    } catch (e) {
      props.onError(e instanceof Error ? e.message : t('aichat.attachDirectoryFailed'))
    } finally {
      setBusy(false)
    }
  }

  const storeFile = async (refsPromise: Promise<ActiveFileEntry[]>, displayName: string) => {
    const sessionAtStart = props.grantSession
    setBusy(true)
    props.onError(null)
    try {
      const refs = await refsPromise
      if (!refs.length) throw new Error(t('aichat.fileNeedsPlugin'))
      props.onPick(refs, displayName, sessionAtStart)
    } catch (e) {
      props.onError(e instanceof Error ? e.message : t('agent.failed'))
    } finally {
      setBusy(false)
    }
  }

  const pick = async () => {
    if (busy) return
    const platform = getPlatform()
    if (props.directory) {
      if (platform.kind === 'desktop') {
        const path = await platform.pickDirectory()
        if (!path) return
        const displayName = path.replace(/[\\/]+$/, '').split(/[\\/]/).pop() || path
        await storeDirectory(services.chat.grantAiNativePath(path, 'directory', props.writable), displayName)
        return
      }
      const input = document.createElement('input')
      input.type = 'file'
      input.setAttribute('webkitdirectory', '')
      input.multiple = true
      input.onchange = () => {
        const files = input.files ? Array.from(input.files) : []
        if (!files.length) return
        const displayName = (files[0] as File & { webkitRelativePath?: string }).webkitRelativePath?.split('/')[0]
          || files[0]!.name
        void storeDirectory(services.chat.uploadAiDirectory(files, props.writable), displayName)
      }
      input.click()
      return
    }
    if (platform.kind === 'desktop') {
      const path = await platform.pickFile()
      if (!path) return
      const displayName = path.replace(/[\\/]+$/, '').split(/[\\/]/).pop() || path
      await storeFile(services.chat.grantAiNativePath(path, 'file', false), displayName)
      return
    }
    fileInputRef.current?.click()
  }

  return (
    <div className="flow-run-file">
      <input
        ref={fileInputRef}
        type="file"
        className="flow-run-file__native"
        tabIndex={-1}
        aria-hidden="true"
        onChange={(event) => {
          const file = event.target.files?.[0]
          event.target.value = ''
          if (!file) return
          void storeFile(services.chat.uploadAiFile(file), file.name)
        }}
      />
      <button
        type="button"
        className={`flow-run-file__pick${props.picked ? ' flow-run-file__pick--done' : ''}`}
        onClick={() => void pick()}
        disabled={busy}
      >
        {busy
          ? <Loader2 size={14} className="flow-spin" />
          : props.directory ? <FolderSearch size={14} /> : <FileSearch size={14} />}
        {props.picked && props.pickedName
          ? props.pickedName
          : props.directory ? t('flows.pickDirectory') : t('flows.pickFile')}
      </button>
      {props.picked && (
        <button type="button" className="cx-iconbtn cx-iconbtn--sm" title={t('common.clear')} onClick={props.onClear}>
          <X size={13} />
        </button>
      )}
      {props.error && <small className="flow-run-file__error">{props.error}</small>}
    </div>
  )
}

function RunStream(props: {
  run: AgentRunStreamState
  onCancel: () => void
  onClose: () => void
  onApprove: () => void
}) {
  const { t } = useTranslation()
  const { run } = props
  return (
    <div className="flow-run-stream">
      <div className={`flow-run-status flow-run-status--${run.status}`}>
        {run.status === 'complete'
          ? <><CheckCircle2 size={15} /> {t('agent.completed')}</>
          : run.status === 'error' || run.status === 'cancelled'
            ? <><AlertCircle size={15} /> {run.status === 'error' ? (run.errorMsg || t('agent.failed')) : t('agent.cancel')}</>
            : <><Loader2 size={15} className="flow-spin" /> {t('agent.running')}</>}
      </div>
      {run.plan?.goal ? <p className="cx-muted flow-run-goal">{run.plan.goal}</p> : null}
      <ol className="flow-run-steps">
        {run.stepList.map((step) => {
          const timing = run.stepTimings.get(step.index)
          const durationMs = timing
            ? (timing.endedAt ?? Date.now()) - timing.startedAt
            : undefined
          return (
            <li key={step.index} className={`flow-run-step flow-run-step--${step.status}`}>
              <span className="flow-run-step__head">
                <strong>{step.toolName || step.description || `#${step.index + 1}`}</strong>
                <small>
                  {step.status}
                  {durationMs !== undefined && step.status !== 'pending'
                    ? ` · ${(durationMs / 1000).toFixed(1)}s`
                    : ''}
                </small>
              </span>
              {step.description && step.description !== step.toolName ? (
                <span className="flow-run-step__desc">{step.description}</span>
              ) : null}
              {run.stepResults.get(step.index) ? (
                <pre className="flow-run-step__result mono">{run.stepResults.get(step.index)}</pre>
              ) : null}
            </li>
          )
        })}
        {!run.stepList.length && (
          <li className="cx-muted flow-run-steps__empty">
            <Loader2 size={14} className="flow-spin" /> {t('agent.running')}
          </li>
        )}
      </ol>
      {run.summary ? <div className="cx-alert cx-alert--success">
        <span className="cx-alert__body">{run.summary}</span>
      </div> : null}
      {run.status === 'error' && !run.errorMsg ? (
        <div className="cx-alert cx-alert--error"><span className="cx-alert__body">{t('agent.failed')}</span></div>
      ) : null}
      {run.awaitingApproval && (
        <div className="cx-alert cx-alert--warn">
          <span className="cx-alert__body">{t('aichat.permissionQuestion')}</span>
        </div>
      )}
      <div className="flow-run-dialog__actions">
        {run.busy && run.awaitingApproval && (
          <button className="cx-btn cx-btn--primary" onClick={props.onApprove}>
            <CheckCircle2 size={14} /> {t('flows.chatApprove')}
          </button>
        )}
        {run.busy
          ? <button className="cx-btn cx-btn--outline" onClick={props.onCancel}><Square size={13} /> {t('agent.cancel')}</button>
          : <button className="cx-btn cx-btn--outline" onClick={props.onClose}>{t('common.close')}</button>}
      </div>
    </div>
  )
}
